apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2018-02-11T08:51:16Z","generation":2,"labels":{"app":"jenkins"},"name":"jenkins","namespace":"default","resourceVersion":"19932","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/jenkins","uid":"b8561f56-0f08-11e8-abcb-025000000001"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"jenkins"}},"spec":{"containers":[{"image":"jenkins/jenkins:lts","imagePullPolicy":"IfNotPresent","name":"jenkins","ports":[{"containerPort":8080,"name":"ui"},{"containerPort":50000,"name":"jnlp"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-02-11T08:51:16Z","lastUpdateTime":"2018-02-11T08:51:16Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2018-02-11T08:51:16Z
  generation: 3
  labels:
    app: jenkins
  name: jenkins
  namespace: default
  resourceVersion: "24932"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/jenkins
  uid: b8561f56-0f08-11e8-abcb-025000000001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          name: ui
          protocol: TCP
        - containerPort: 50000
          name: jnlp
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: jenkins-home
        hostPath:
          path: /Users/takizawatakeshi/data/jenkins
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-02-11T08:51:16Z
    lastUpdateTime: 2018-02-11T08:51:16Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
